node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /home/weesolutionsit/api/server.js
- /usr/local/lsws/fcgi-bin/lsnode.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/weesolutionsit/api/server.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/weesolutionsit/api/server.js',
    '/usr/local/lsws/fcgi-bin/lsnode.js'
  ]
}
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /home/weesolutionsit/api/server.js
- /usr/local/lsws/fcgi-bin/lsnode.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/weesolutionsit/api/server.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/weesolutionsit/api/server.js',
    '/usr/local/lsws/fcgi-bin/lsnode.js'
  ]
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Pool.js:48:16)
    at /home/weesolutionsit/api/tools.js:136:18
    at new Promise (<anonymous>)
    at Object.$.Connection (/home/weesolutionsit/api/tools.js:135:10)
    at cacheDB (/home/weesolutionsit/api/scraper.js:249:22)
    at Main (/home/weesolutionsit/api/scraper.js:21:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Pool.js:48:16)
    at /home/weesolutionsit/api/tools.js:136:18
    at new Promise (<anonymous>)
    at Object.$.Connection (/home/weesolutionsit/api/tools.js:135:10)
    at cacheDB (/home/weesolutionsit/api/scraper.js:249:22)
    at Main (/home/weesolutionsit/api/scraper.js:21:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Pool.js:48:16)
    at /home/weesolutionsit/api/tools.js:136:18
    at new Promise (<anonymous>)
    at Object.$.Connection (/home/weesolutionsit/api/tools.js:135:10)
    at cacheDB (/home/weesolutionsit/api/scraper.js:249:22)
    at Main (/home/weesolutionsit/api/scraper.js:21:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Pool.js:48:16)
    at /home/weesolutionsit/api/tools.js:136:18
    at new Promise (<anonymous>)
    at Object.$.Connection (/home/weesolutionsit/api/tools.js:135:10)
    at cacheDB (/home/weesolutionsit/api/scraper.js:249:22)
    at Main (/home/weesolutionsit/api/scraper.js:21:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Pool.js:48:16)
    at /home/weesolutionsit/api/tools.js:136:18
    at new Promise (<anonymous>)
    at Object.$.Connection (/home/weesolutionsit/api/tools.js:135:10)
    at cacheDB (/home/weesolutionsit/api/scraper.js:249:22)
    at Main (/home/weesolutionsit/api/scraper.js:21:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Pool.js:48:16)
    at /home/weesolutionsit/api/tools.js:136:18
    at new Promise (<anonymous>)
    at Object.$.Connection (/home/weesolutionsit/api/tools.js:135:10)
    at cacheDB (/home/weesolutionsit/api/scraper.js:249:22)
    at Main (/home/weesolutionsit/api/scraper.js:21:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Pool.js:48:16)
    at /home/weesolutionsit/api/tools.js:136:18
    at new Promise (<anonymous>)
    at Object.$.Connection (/home/weesolutionsit/api/tools.js:135:10)
    at cacheDB (/home/weesolutionsit/api/scraper.js:249:22)
    at Main (/home/weesolutionsit/api/scraper.js:21:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/home/weesolutionsit/nodevenv/api/16/lib/node_modules/mysql/lib/Pool.js:48:16)
    at /home/weesolutionsit/api/tools.js:136:18
    at new Promise (<anonymous>)
    at Object.$.Connection (/home/weesolutionsit/api/tools.js:135:10)
    at cacheDB (/home/weesolutionsit/api/scraper.js:249:22)
    at Main (/home/weesolutionsit/api/scraper.js:21:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
